
import __ASTRO_IMAGE_IMPORT_ZS8MgX from "../../assets/images/blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpredictive-analytics-startups.md";
import __ASTRO_IMAGE_IMPORT_Z1YAGM from "../../assets/images/blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freal-time-data-processing.md";
import __ASTRO_IMAGE_IMPORT_Z2mpzBk from "../../assets/images/blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdata-driven-analytics.md";
import __ASTRO_IMAGE_IMPORT_11sc8L from "../../assets/images/blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fscalable-data-pipelines.md";
import __ASTRO_IMAGE_IMPORT_wPjl9 from "../../assets/images/blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffuture-business-intelligence.md";
import __ASTRO_IMAGE_IMPORT_Z1QiNFO from "../../assets/images/blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Foptimizing-performance-web-scale.md";
import __ASTRO_IMAGE_IMPORT_2fbBdg from "../../assets/images/testimonial1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freal-time-data-processing.md";
import __ASTRO_IMAGE_IMPORT_Z1SQMQ0 from "../../assets/images/testimonial1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fscalable-data-pipelines.md";
import __ASTRO_IMAGE_IMPORT_Z2py51c from "../../assets/images/testimonial2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Foptimizing-performance-web-scale.md";
import __ASTRO_IMAGE_IMPORT_he1xk from "../../assets/images/testimonial2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpredictive-analytics-startups.md";
import __ASTRO_IMAGE_IMPORT_Z2pxMSt from "../../assets/images/testimonial3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdata-driven-analytics.md";
import __ASTRO_IMAGE_IMPORT_qa9hN from "../../assets/images/testimonial3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffuture-business-intelligence.md";
export default new Map([["../../assets/images/blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpredictive-analytics-startups.md", __ASTRO_IMAGE_IMPORT_ZS8MgX], ["../../assets/images/blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freal-time-data-processing.md", __ASTRO_IMAGE_IMPORT_Z1YAGM], ["../../assets/images/blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdata-driven-analytics.md", __ASTRO_IMAGE_IMPORT_Z2mpzBk], ["../../assets/images/blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fscalable-data-pipelines.md", __ASTRO_IMAGE_IMPORT_11sc8L], ["../../assets/images/blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffuture-business-intelligence.md", __ASTRO_IMAGE_IMPORT_wPjl9], ["../../assets/images/blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Foptimizing-performance-web-scale.md", __ASTRO_IMAGE_IMPORT_Z1QiNFO], ["../../assets/images/testimonial1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freal-time-data-processing.md", __ASTRO_IMAGE_IMPORT_2fbBdg], ["../../assets/images/testimonial1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fscalable-data-pipelines.md", __ASTRO_IMAGE_IMPORT_Z1SQMQ0], ["../../assets/images/testimonial2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Foptimizing-performance-web-scale.md", __ASTRO_IMAGE_IMPORT_Z2py51c], ["../../assets/images/testimonial2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpredictive-analytics-startups.md", __ASTRO_IMAGE_IMPORT_he1xk], ["../../assets/images/testimonial3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdata-driven-analytics.md", __ASTRO_IMAGE_IMPORT_Z2pxMSt], ["../../assets/images/testimonial3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffuture-business-intelligence.md", __ASTRO_IMAGE_IMPORT_qa9hN]]);
		