export const positions = [
  {
    slug: 'senior-frontend-engineer',
    title: 'Senior Frontend Engineer',
    description: 'Build the next generation of real-time dashboards and data visualization tools',
    location: 'Remote',
    type: 'Full-time',
    department: 'Engineering',
    about:
      "We're looking for a Senior Frontend Engineer to lead the development of our real-time dashboard platform. You'll work closely with our design and data teams to create intuitive, high-performance interfaces that help thousands of developers visualize their data.",
    responsibilities: [
      'Design and implement new dashboard components and data visualizations',
      'Optimize rendering performance for real-time data streams',
      'Collaborate with product and design teams on new features',
      'Mentor junior engineers and contribute to technical decision-making',
      'Write clean, maintainable, and well-tested code',
    ],
    requirements: [
      '5+ years of experience with modern frontend frameworks',
      'Strong proficiency in TypeScript and CSS',
      'Experience with data visualization libraries (D3, Recharts, etc.)',
      'Understanding of performance optimization techniques',
      'Excellent communication and collaboration skills',
    ],
  },
  {
    slug: 'data-engineer',
    title: 'Data Engineer',
    description: 'Design and optimize our data processing pipeline to handle billions of events',
    location: 'Remote',
    type: 'Full-time',
    department: 'Engineering',
    about:
      "Join our data infrastructure team to build and maintain the pipelines that process billions of events daily. You'll design scalable systems that power our analytics engine and enable real-time insights for our users.",
    responsibilities: [
      'Design and build scalable data pipelines for real-time and batch processing',
      'Optimize query performance across large datasets',
      'Implement data quality monitoring and alerting systems',
      'Collaborate with product teams to define data models',
      'Contribute to our open-source data tools',
    ],
    requirements: [
      '4+ years of experience in data engineering',
      'Strong SQL skills and experience with distributed databases',
      'Experience with stream processing frameworks (Kafka, Flink, etc.)',
      'Proficiency in Python or Go',
      'Understanding of data warehousing concepts',
    ],
  },
  {
    slug: 'product-designer',
    title: 'Product Designer',
    description: 'Shape the UX of complex data into simple, elegant experiences',
    location: 'Hybrid - SF',
    type: 'Full-time',
    department: 'Design',
    about:
      "We need a Product Designer who can turn complex data concepts into beautiful, intuitive interfaces. You'll own the end-to-end design process for key product areas, working with engineers and data scientists to create experiences that delight developers.",
    responsibilities: [
      'Lead design for new product features from concept to launch',
      'Create wireframes, prototypes, and high-fidelity designs',
      'Conduct user research and usability testing',
      'Build and maintain our design system',
      'Partner with engineering to ensure pixel-perfect implementation',
    ],
    requirements: [
      '4+ years of product design experience, preferably in B2B/SaaS',
      'Strong portfolio demonstrating data-heavy interface design',
      'Proficiency in Figma and prototyping tools',
      'Experience with design systems',
      'Understanding of frontend development concepts',
    ],
  },
  {
    slug: 'devrel-engineer',
    title: 'DevRel Engineer',
    description: 'Help developers succeed with our platform, API, and integrations',
    location: 'Remote',
    type: 'Full-time',
    department: 'Developer Relations',
    about:
      "As a DevRel Engineer, you'll be the bridge between our engineering team and the developer community. You'll create content, build sample projects, speak at conferences, and help shape our API and documentation to ensure every developer has a great experience.",
    responsibilities: [
      'Create tutorials, guides, and sample applications',
      'Engage with the developer community through talks and social media',
      'Provide feedback to product teams based on developer needs',
      'Maintain and improve our API documentation',
      'Build and nurture our open-source community',
    ],
    requirements: [
      '3+ years of software engineering experience',
      'Excellent writing and public speaking skills',
      'Experience creating developer-facing content',
      'Familiarity with analytics and data tools',
      'Active presence in developer communities',
    ],
  },
  {
    slug: 'backend-engineer',
    title: 'Backend Engineer',
    description: 'Scale our real-time analytics engine and build new API endpoints',
    location: 'Remote',
    type: 'Full-time',
    department: 'Engineering',
    about:
      "We're looking for a Backend Engineer to help scale our analytics engine to handle the next order of magnitude of data. You'll work on our core API, build new endpoints, and optimize our infrastructure for performance and reliability.",
    responsibilities: [
      'Design and implement new API endpoints and services',
      'Optimize system performance and reduce latency',
      'Build monitoring and observability tooling',
      'Participate in architecture discussions and code reviews',
      'Contribute to our infrastructure-as-code practices',
    ],
    requirements: [
      '4+ years of backend engineering experience',
      'Strong proficiency in Node.js, Go, or Rust',
      'Experience with distributed systems and microservices',
      'Understanding of database design and optimization',
      'Experience with cloud platforms (AWS, GCP, or Azure)',
    ],
  },
  {
    slug: 'technical-writer',
    title: 'Technical Writer',
    description: 'Create clear, comprehensive documentation for developers and teams',
    location: 'Remote',
    type: 'Contract',
    department: 'Developer Relations',
    about:
      "We need a Technical Writer to create world-class documentation that helps developers get started quickly and succeed with our platform. You'll work with engineers to understand complex features and translate them into clear, actionable guides.",
    responsibilities: [
      'Write and maintain API reference documentation',
      'Create getting-started guides and tutorials',
      'Develop code samples and integration guides',
      'Improve documentation site structure and navigation',
      'Review and edit content from engineering contributors',
    ],
    requirements: [
      '3+ years of technical writing experience',
      'Ability to read and understand code in multiple languages',
      'Experience with docs-as-code workflows',
      'Strong attention to detail and consistency',
      'Experience documenting APIs and developer tools',
    ],
  },
];
